"""The map as text: Mermaid diagrams and Markdown tables (spec §5, §6).

Refusals are not drawn. Standard UML does not draw an event a state does
not handle, and the grid is their conventional home (spec §2).
"""
from __future__ import annotations

import re

from statemap.model import Model

NOTICE = "<!-- Generated by scripts/state-map-generate from docs/state-map/data. Do not edit. -->"
ENDPOINTS_LINK = "Every answer of every endpoint, with its cause and how to try it: [endpoints](endpoints.md)"


def clean(text: str) -> str:
    """Text safe inside a Mermaid label: no colon, brace, quote mark, hash or semicolon."""
    return " ".join(re.sub(r'[:;{}"#<>|]', " ", text).split())


def cell_text(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def short(action: str) -> str:
    return action.replace("/api/v1", "", 1)


def node(region_id: str, state: str) -> str:
    return f"{region_id.replace('.', '_')}__{state}"


def told(model: Model, row: dict) -> str:
    """The action in words. A request your partner makes is their act, so it is said as theirs."""
    label = model.label(row["action"])
    if row["actor"] == "partner" and any(e["id"] == row["action"] for e in model.endpoints):
        label = re.sub(r"\byou\b", "they", re.sub(r"\byour\b", "their", label))
    return label


def _on_arrow(model: Model, row: dict) -> str:
    """An arrow already names its actor, so an event's label drops its own subject."""
    label = told(model, row)
    if row["actor"] != "you" and any(e["id"] == row["action"] for e in model.events):
        label = re.sub(r"^(your partner|the) ", "", label)
    return clean(label)


def _edges(model: Model, region_id: str) -> dict:
    edges = {}
    for row in model.rows:
        if row["region"] == region_id and row["outcome"] == "ok" and row["to"] != row["from"]:
            labels = edges.setdefault((row["from"], row["to"]), {}).setdefault(row["actor"], [])
            label = _on_arrow(model, row)
            if label not in labels:
                labels.append(label)
    return edges


def _edge_label(by_actor: dict) -> str:
    parts = []
    for actor, labels in by_actor.items():
        text = labels[0] if len(labels) == 1 else f"{len(labels)} actions"
        parts.append(f"{actor} - {text}")
    return ", ".join(parts)


def state_diagram(model: Model, region_id: str) -> str:
    """One region, drawn flat: a class cannot be relied on inside a composite state."""
    lines = ["stateDiagram-v2"]
    unbuilt = []
    for state in model.regions()[region_id]["states"]:
        lines.append(f'    state "{clean(state["label"])}" as {node(region_id, state["id"])}')
        if not state.get("built", True):
            unbuilt.append(node(region_id, state["id"]))
    for (source, target), by_actor in _edges(model, region_id).items():
        lines.append(f"    {node(region_id, source)} --> {node(region_id, target)}: {_edge_label(by_actor)}")
    if unbuilt:
        lines.append("    classDef unbuilt fill:#eeeeee,stroke:#aaaaaa,color:#888888")
        lines += [f"    class {name} unbuilt" for name in unbuilt]
    return "\n".join(lines)


def _answer(row: dict) -> str:
    if row["outcome"] == "unreachable":
        return "not reachable"
    if row["outcome"] == "refused":
        return f"{row['status']} `{row['code']}`"
    if row["to"] == row["from"]:
        return f"{row['status']} stays"
    return f"{row['status']} → `{row['to']}`"


def _cell(row: dict) -> str:
    return _answer(row) + (f" ({cell_text(row['when'])})" if row["when"] else "")


def _table(header: list, rows: list) -> str:
    lines = ["| " + " | ".join(header) + " |", "|---" * len(header) + "|"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


def grid_table(model: Model, region_id: str) -> str:
    states = model.states(region_id, built_only=True)
    mine = [r for r in model.rows if r["region"] == region_id and r["actor"] == "you"]
    body = []
    for action in dict.fromkeys(r["action"] for r in mine):
        cells = []
        for state in states:
            rows = [r for r in mine if r["action"] == action and r["from"] == state]
            cells.append("<br>".join(_cell(r) for r in rows) or "**EMPTY**")
        body.append([f"{cell_text(model.label(action))}<br>`{short(action)}`"] + cells)
    return _table(["Action"] + [f"`{s}`" for s in states], body) if body else ""


def _you_can(model: Model, region_id: str) -> str:
    rows = [
        [f"`{r['from']}`", cell_text(told(model, r)), cell_text(r["when"]),
         "stays" if r["to"] == r["from"] else f"`{r['to']}`", cell_text(r["reason"]), r["evidence"]]
        for r in model.rows
        if r["region"] == region_id and r["actor"] == "you" and r["outcome"] == "ok"
    ]
    return _table(["In", "Action", "When", "Leads to", "Why", "Evidence"], rows) if rows else ""


def _refusals(model: Model, region_id: str) -> str:
    rows = [
        [f"`{r['from']}`", cell_text(told(model, r)), cell_text(r["when"]), f"{r['status']} `{r['code']}`",
         cell_text(r["reason"]), r["rule"], r["evidence"]]
        for r in model.rows
        if r["region"] == region_id and r["actor"] == "you" and r["outcome"] == "refused"
    ]
    return _table(["In", "Action", "When", "Answer", "Why", "Rule", "Evidence"], rows) if rows else ""


def _without_you(model: Model, region_id: str) -> str:
    rows = [
        [f"`{r['from']}`", cell_text(told(model, r)), r["actor"], cell_text(r["when"]), f"`{r['to']}`",
         cell_text(r["reason"]), r["evidence"]]
        for r in model.rows
        if r["region"] == region_id and r["actor"] != "you"
    ]
    return _table(["In", "What happens", "Who", "When", "Leads to", "Why", "Evidence"], rows) if rows else ""


def _gaps(model: Model, machine: dict) -> str:
    regions = {r["id"] for r in machine["regions"]}
    mine = {r["action"] for r in model.rows if r["region"] in regions}
    rows = [
        [f"`{short(g['endpoint'])}`", str(g["status"]), cell_text(g["note"])]
        for g in model.gaps
        if g["endpoint"] in mine
    ]
    return _table(["Endpoint", "Status", "What the code does"], rows) if rows else ""


def machine_md(model: Model, machine_id: str) -> str:
    machine = next(m for m in model.machines if m["id"] == machine_id)
    parts = [
        NOTICE,
        f"# The {machine['label'].lower()} machine",
        f"Describes `main @ {model.stamp}`. How to read this: [README](README.md).",
        *([ENDPOINTS_LINK] if model.endpoints else []),
        "Each region below has its own diagram. Each arrow says who acts: you, your partner or the "
        "system. Refusals are not drawn; they are in the tables. Grey means designed or only partly "
        "built, and no endpoint reaches it.",
    ]
    for region in machine["regions"]:
        parts += [f"## {region['label']}", "```mermaid\n" + state_diagram(model, region["id"]) + "\n```"]
        sections = (
            ("Every action in every state", grid_table(model, region["id"])),
            ("You can", _you_can(model, region["id"])),
            ("Refused here", _refusals(model, region["id"])),
            ("Happens without you", _without_you(model, region["id"])),
        )
        for title, text in sections:
            if text:
                parts += [f"### {title}", text]
    gaps = _gaps(model, machine)
    if gaps:
        parts += [
            "## Where the contract is silent",
            "The code answers these and `contracts/openapi.json` does not document them.",
            gaps,
        ]
    return "\n\n".join(parts) + "\n"


def _every_answer(model: Model, action: str) -> str:
    regions = list(model.regions())
    rows = [r for r in model.rows if r["action"] == action and r["actor"] == "you"]
    rows.sort(key=lambda r: (regions.index(r["region"]), model.states(r["region"]).index(r["from"])))
    body = [
        [f"`{r['region']}`", f"`{r['from']}`", cell_text(r["when"]), _answer(r), cell_text(r["reason"]),
         r["rule"], r["evidence"]]
        for r in rows
    ]
    return _table(["Region", "In", "When", "Answer", "Why", "Rule", "Evidence"], body) if body else ""


def _card(model: Model, card: dict) -> list:
    needs = "an access token" if card["auth"] == "bearer" else "no access token"
    parts = [f"### {short(card['id'])}", card["summary"], f"**Needs:** {needs}."]
    if card["headers"]:
        parts.append("\n".join(f"- {header}" for header in card["headers"]))
    parts.append(f"**Try it:**\n\n```sh\n{card['curl']}\n```")
    errors = [
        [str(e["status"]), f"`{e['code']}`", cell_text(e["reason"]), e["evidence"]]
        for e in card["requestErrors"]
    ]
    gaps = [[str(g["status"]), cell_text(g["note"])] for g in model.gaps if g["endpoint"] == card["id"]]
    sections = (
        ("Every answer", _every_answer(model, card["id"])),
        ("Whatever the state", _table(["Status", "Code", "Why", "Evidence"], errors) if errors else ""),
        ("The contract is silent on", _table(["Status", "What the code does"], gaps) if gaps else ""),
    )
    for title, text in sections:
        if text:
            parts += [f"#### {title}", text]
    return parts


def endpoints_md(model: Model) -> str:
    """The per-endpoint drill-down (spec §5 view 2): every card, and every answer it can give."""
    parts = [
        NOTICE,
        "# Every endpoint",
        f"Describes `main @ {model.stamp}`. Every answer each endpoint can give, with its cause and "
        "how to try it. How to read this: [README](README.md).",
        "## Errors that can follow any call",
        "Any of these can follow any endpoint below. They are not repeated under each one.",
        _table(["Status", "Code", "Why"],
               [[str(e["status"]), f"`{e['code']}`", cell_text(e["reason"])] for e in model.everywhere]),
    ]
    for entry in model.everywhere:
        if entry.get("rowsAllowedIn"):
            regions = " and ".join(f"`{r}`" for r in entry["rowsAllowedIn"])
            parts.append(
                f"`{entry['status']} {entry['code']}` is also a row in the regions {regions}, "
                "where it depends on the state."
            )
    for machine in model.machines:
        cards = [c for c in model.endpoints if c["machine"] == machine["id"]]
        if cards:
            parts.append(f"## {machine['label']}")
            for card in cards:
                parts += _card(model, card)
    return "\n\n".join(parts) + "\n"


def sequence_diagram(model: Model, journey: dict) -> str:
    rows = {r["id"]: r for r in model.rows}
    lines = [
        "sequenceDiagram",
        "    actor You",
        "    actor Partner",
        "    participant API",
        "    participant Job as The service, on its own schedule",
    ]
    groups = []
    for step in journey["steps"]:
        if step.get("sameRequest") is True and groups:
            groups[-1].append(rows[step["row"]])
        else:
            groups.append([rows[step["row"]]])
    for group in groups:
        row = group[0]
        who = {"you": "You", "partner": "Partner", "system": "Job"}[row["actor"]]
        lines.append(f"    {who}->>API: {clean(told(model, row))}")
        regions = ", ".join(f"{r['region']} is {r['to']}" for r in group)
        if row["outcome"] == "refused":
            lines.append(f"    API-->>{who}: {row['status']} {row['code']}")
        elif row["status"] is None:
            lines.append(f"    Note over API: {regions}")
        else:
            lines.append(f"    API-->>{who}: {row['status']}, {regions}")
    return "\n".join(lines)


def journeys_md(model: Model) -> str:
    rows = {r["id"]: r for r in model.rows}
    parts = [
        NOTICE,
        "# Journeys",
        f"Describes `main @ {model.stamp}`. Each journey is a path through the three machines, "
        "taken from doc 02. How to read this: [README](README.md).",
    ]
    for journey in model.journeys:
        parts.append(f"## {journey['id']}: {journey['title']}")
        steps = []
        for number, step in enumerate(journey["steps"], start=1):
            row = rows[step["row"]]
            note = f" {step['note']}" if step.get("note") else ""
            same = "(the same request) " if step.get("sameRequest") is True else ""
            steps.append(f"{number}. {same}**{row['actor']}**: {told(model, row)}. {row['reason']}{note}")
        parts.append("\n".join(steps))
        parts.append("```mermaid\n" + sequence_diagram(model, journey) + "\n```")
    return "\n\n".join(parts) + "\n"


