spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moyi
    username: moyi
    password: moyi_dev_only
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
